### ISSUE TITLE
[Szolgáltatások] WordPress

### ISSUE THREAD

**Issue by mzoli95** [mzoli95/zmbh#12]
[Info] Teljes körű WordPress megoldások, kezdve a testreszabott témáktól az egyedi bővítményekig.

Beszéljük meg, hogy milyen wp oldalakat csinálunk, csak sima portfólió oldalakat? vagy e-commerence wp oldalakat is?
Mi az, amiket vállalunk, hogy megtanuljuk.

Milyen árakon dolgozzunk?
Statikus illetve dinamikus oldalanként kellenének az árak, plusz üzemeltetési árak is kellenének, ebbe bele kell venni hogy melyik szolgáltatónál béreljük a szervert, domaint.

**Comment by mzoli95** [comment]
Weboldal Készítés és Webdesign Szolgáltatások:

Kínálj weboldal készítési és webdesign szolgáltatásokat vállalkozásoknak és magánszemélyeknek.
Testreszabható sablonok és stílusok használata a céges arculathoz igazítva.
SEO-optimalizálás a weboldalak jobb keresési rangsorozásához.
Vezetőgenerálás és konverzióoptimalizálás.
Blogolási és Tartalomkészítési Szolgáltatások:

Hozz létre és kezelj blogokat és tartalomkészítési szolgáltatásokat.
SEO-barát tartalom készítése és terjesztése.
Tartalomstratégia kidolgozása és tartalomkezelés.
E-commerce és Online Áruházak:

Fejlessz webáruházakat és e-commerce megoldásokat WordPress alapokon.
Termékek és kategóriák kezelése.
Online fizetési rendszerek integrálása.
Raktárkészletkezelés és rendelések kezelése.
Digitális Marketing és Szociális Média Kezelés:

Nyújts digitális marketing és szociális média kezelési szolgáltatásokat.
Facebook, Instagram, Twitter és más platformok kezelése és tartalom terjesztése.
Analitikai és riporting szolgáltatások.

**Comment by Balage1234** [comment]
Hát amiket néztünk pár ezer forint egy domain szolgáltatás bérlése azt 1in1 bele kéne foglalni az árba. De az is lehet hogy az ügyfélnek ez már mind megvan csak egy sima sablon kell neki

**Comment by Balage1234** [comment]
Én szerintem kezdetlegesen ilyen 20 euró lenne a reális max nem? amioor néztük kb az átlag így dolgozik az elején persze kivéve aki full olcsó :D Persze ez függ a project bonyolultságától

**Comment by Balage1234** [comment]
És véleményem szerint az a fodrász meg egy ilyen fotó appliáció eléggé jó portfóliónak ilyen vizuális és effect téren.
Továbbbá az árra visszamenve, attól is függ az ár, hogy most ingyenes add-onokat használnunk vagy előfizetünk valamilyen fizetős editorra. Erről még azért beszélni meg kutatni kell, hogy mi van a piacon jelenleg, pl aki divit használ, az milyen árral dolgozik plusz nagyobb beruházás nemtudom, talán megkéne nézni elöszőr hogy mire van kereslet nem?

**Comment by mzoli95** [comment]
amire csinálsz keresletet, arra lesz kereslet :D
divi/elementort elhagynám egyelőre én is. default szerkesztőt kéne majd mókolni, de nekem mostanság nem lesz rá időm, ami lesz azt lehet inkább a BE részébe teszem, ha gondolod nyomasd a WP-t, ha végzünk a keret FE-el :)

**Comment by Balage1234** [comment]
Persze mivel van mellette melónk is ezért az a prio, én benne vagyok hogy nézegetem a WP-t
