### ISSUE TITLE
[Termékeink] Saját termékeink, ötletek

### ISSUE THREAD

**Issue by mzoli95** [mzoli95/zmbh#18]
1, DMS.
2. EYM.
3. S.O.S.  szervíz
4. Ügyfélnyilvántartó

**Comment by mzoli95** [comment]
seo optimalizáció vizsgáló kis service

**Comment by mzoli95** [comment]
saját WP oldalak, pl keret (sablon) a kutyakozmetikusoknak, fodrászoknak

**Comment by Balage1234** [comment]
Igazából mindent amiről szó esett felsoroltál, per pillanat én se tudok többet
