### ISSUE TITLE
[FE] dropdown close directive

### ISSUE THREAD

**Issue by mzoli95** [mzoli95/zmbh#28]

**Comment by Balage1234** [comment]
I will test it today on ios androis and pc

**Comment by mzoli95** [comment]
what was your results?

**Comment by Balage1234** [comment]
It worked great, but tbh I think they need more space between each
![image](https://github.com/mzoli95/zmbh/assets/152930786/34c86621-afd7-4651-82ed-fcaddb83936a)

**Comment by Balage1234** [comment]
They are almost on each other

**Comment by mzoli95** [comment]
we have ongoing task for the responsivity. here is the matter is to be able close if you click out of the dropdown box (or just if you've clicked a link inside the dropdown box)
