### ISSUE TITLE
[FE] Header improvements

### ISSUE THREAD

**Issue by MarkPatkai** [mzoli95/zmbh#29]
- [x] Gradient Color on header
- [x] Drop-shadow on the navbar to imitate a bevel effect
- [x] border-radius (white) ellipsis on buttons
- [x] buttons should be low-capital and Arial
- [x] buttons should have bigger font-size
- [x] Login and Registration can be icons with tooltip (optional, font-awesome package)

**Comment by mzoli95** [comment]
Icons has been changed via FA
buttons got 18px arial style with 2px solid ellipsis radius
navbar got gradient color from bottom right corner to top left
