### ISSUE TITLE
[FE] About us - Team improvements

### ISSUE THREAD

**Issue by mzoli95** [mzoli95/zmbh#32]
![image](https://github.com/mzoli95/zmbh/assets/145398583/2a810849-6082-4018-8a47-56e5500bd6a0)

- [x] Replace the text and format it
- [x] Put the text in the center
- [x] Make the card darker instead of white and use border-radius on the edges

**Comment by Balage1234** [comment]
All right, this will be my first job today after I finished my work

**Comment by Balage1234** [comment]
Replace a text with what, do you have any idea in your mind?

**Comment by Balage1234** [comment]
![image](https://github.com/mzoli95/zmbh/assets/152930786/76818ed5-3ae1-43f2-bad1-7d9519940792)

**Comment by Balage1234** [comment]
I don't know if this meet with your expectations._

**Comment by mzoli95** [comment]
seems great
if u think you can enhance the descriptions

**Comment by mzoli95** [comment]
seems much better

**Comment by Balage1234** [comment]
I've already enhanced the sice of the description

**Comment by mzoli95** [comment]
nicely done. don't forget to push
