### ISSUE TITLE
[FE] Why choose us enhancement

### ISSUE THREAD

**Issue by mzoli95** [mzoli95/zmbh#36]
![image](https://github.com/mzoli95/zmbh/assets/145398583/8f867aff-c211-49c7-b679-d29ef9207336)

- [x] First tab is done, do the same style with the other tabs inside

**Comment by Balage1234** [comment]
That tab looks, astonishing !

**Comment by mzoli95** [comment]
would you like to do the remaining tabs?

**Comment by Balage1234** [comment]
Yes I would

**Comment by Balage1234** [comment]
Done, and I also eliminated the inline styling

**Comment by mzoli95** [comment]
nicely done
