### ISSUE TITLE
[FE] What can we use insted of Competetion matrixes?

### ISSUE THREAD

**Issue by mzoli95** [mzoli95/zmbh#37]

**Comment by mzoli95** [comment]
e.g.: our stacks,  where were we work or something else

**Comment by Balage1234** [comment]
I think we need to emphasize our strength, and that we are willing to learn new things, right? What do you think?

**Comment by mzoli95** [comment]
we should put our strength into the team section under the about us

**Comment by Balage1234** [comment]
Maybe, but this design is so good, so I don't know how to redesign that

**Comment by mzoli95** [comment]
the design is good  on the about-us -> team section. Later we can enhance the text and put our strenghts

for replacing competetion matrix we should put our stacks to the main page (I don't have other idea to put to the home page right now) instead of the matrixes

**Comment by Balage1234** [comment]
Yes I agree
