### ISSUE TITLE
About-us -> csapat -> szebb elrendezés

### ISSUE THREAD

**Issue by mzoli95** [mzoli95/zmbh#4]
About-us -> csapat -> szebb elrendezés kellene, illetve a blokk háttere is fehér, az nekünk nem jó.
![image](https://github.com/mzoli95/zmbh/assets/145398583/252a3816-0c2a-4666-8ff8-f05b6e5fde56)

**Comment by mzoli95** [comment]
a kor ne legyen benne

**Comment by Balage1234** [comment]
a szöveg jelen pillanatban csak placeholder semmit se én írtam belőle

**Comment by Balage1234** [comment]
és a színhez se nyúltam

**Comment by Balage1234** [comment]
viszont a struktúrára nemtudom szerinted mi lenne a jó?

**Comment by mzoli95** [comment]
rád bízom, én valami hasonlón indulnék el:
https://material.angular.io/components/card/examples
![image](https://github.com/mzoli95/zmbh/assets/145398583/7d6d9cad-9317-483c-bb6f-c32cd7e7bbe7)

**Comment by mzoli95** [comment]
egymás mellé gondolnám
