### ISSUE TITLE
Projektek a home page oldalon

### ISSUE THREAD

**Issue by mzoli95** [mzoli95/zmbh#5]
Úgy gondoltam el, hogy nem két oszlopos megoldásunk lesz mint most (szöveg és kép), hanem mondjuk négyzetek (akár mat card) alapon lennének megjelenítve a projektek, csatolok egy képet hozzá, mire gondoltam (2. kép), elő kellene készíteni őket, elég ha statikusan felveszel mondjuk 4 kockát egymás mellé (nem kell mindet a főoldalra tenni, csak a jobb projektjeinket majd)
alá pedig legyen egy gomb, az pedig vigyen a Projectjeink oldalra majd, ahol mindegyiket kifejtjük.

![image](https://github.com/mzoli95/zmbh/assets/145398583/88c3f2ab-709f-4e4b-89e9-0f1b1b7ec02c)

![image](https://github.com/mzoli95/zmbh/assets/145398583/df546f7a-b803-4ae2-940e-b17ed3a5c1e6)

**Comment by mzoli95** [comment]
mivel minden blokk a weboldalra fog vinni, ezért ha az innovate1.png nevü képet betöltöd minden kockába az is jó, pontosítok, NEM MAT-CARD kell, elég ha csak a képet rakok egymás mellé (4db) , és border-t adsz nekik.

**Comment by mzoli95** [comment]
https://ng-bootstrap.github.io/#/components/carousel/api

**Comment by Balage1234** [comment]
Probáltam, de valamiért nálam nem jeleníti meg a képeket
Hiába adom meg azokat amik nekünk hpzzá vannak adve csak a 2 nyíl jelenik meg és ennyi

**Comment by mzoli95** [comment]
attach your code as well pls
have you used the correct path to reach the images?
