### ISSUE TITLE
[Teszt] Email küldés

### ISSUE THREAD

**Issue by mzoli95** [mzoli95/zmbh#9]
nézz meg különböző eseteket, ha nem megy a szerver küld el kétszer a kapcsolat formon belül az adatokat, mindkétszer futnia kell a notification servicenek, ezt csináld meg akkor is, ha rossz az email formátum, illetve, ha jó minden, akkor is kétszer próbáld meg elküldeni és figyeld látsz-e bármi hibát (console-log ot is nézd, meg a hálózat fület az inspectben)

node szervert egyszerűen tudod futtatni: node .\index.js
és ha azt akarod, hogy hibára fusson az email formátummal, akkor a !-t vedd ki innen:
  if (!emailRegex.test(email)) {
    return res
      .status(400)
      .send({ message: "Hiba történt: Érvénytelen email cím" });
  }

**Comment by Balage1234** [comment]
Nem tudom futtatni a node.js filet akármit is csinálok

**Comment by Balage1234** [comment]
![image](https://github.com/mzoli95/zmbh/assets/152930786/da937efa-2c03-4f8c-82e6-40b1f0f2ef98)

**Comment by Balage1234** [comment]
Nélkülde meg erre az hibára fut:
![image](https://github.com/mzoli95/zmbh/assets/152930786/939fe267-814c-4dc3-93d7-fbb71a2f644e)

**Comment by Balage1234** [comment]
valamiért más esetet nem is tudok előhozni

**Comment by mzoli95** [comment]
The error what you got is good for us because it's not able to reach the backend server. so that's good for us, the notification service is working correctly there. haven't you experiences any freeze?
you should do an "npm i" before you start your manual tests
![image](https://github.com/mzoli95/zmbh/assets/145398583/28e896c0-86f0-459a-a813-a4570bd6b6fd)

**Comment by Balage1234** [comment]
most erre a hibára fut
![image](https://github.com/mzoli95/zmbh/assets/152930786/ad9665aa-81ac-41ef-8b36-15e6239d9092)

**Comment by Balage1234** [comment]
A szervert sikerült elindítani rendesen

**Comment by Balage1234** [comment]
The HTTP status code 500 is a generic error response. It means that the server encountered an unexpected condition that prevented it from fulfilling the request. This error is usually returned by the server when no other error code is suitable.

**Comment by Balage1234** [comment]
.env file létrehozatala:
SMTP_HOST=smtp.gmail.com
SMTP_PORT=465
SMTP_USERNAME=zmbhsolutions@gmail.com
SMTP_PASSWORD=wolh hhcp ojwm pqwb
SMTP_SECURE=true
JWT_SECRET=1q2w3e4r5t6m7c8x
tarartalommal. Ezután az email küldés hibátlanül működik
